### ISSUE TITLE
Need example of Bearer auth

### ISSUE THREAD

**Issue by bubnenkoff** [rebolek/red-tools#4]
I am trying to do Bearer auth.

I use next request:
```
answer: send-request/auth http://localhost:8529/_db/ztest/_api/collection/protocols 'POST 'Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjEuNTkzMTcyOTU4NTg4MzQ3OGUrNiwiZXhwIjoxNTk1NzY0OTU4LCJpc3MiOiJhcmFuZ29kYiIsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXIifQ==.a9L7AGDqjjZv1OdFYmT_uFUGLbX_NBva00UoUQXhSns="
```
```
*** Script Error: invalid argument: none
*** Where: write
*** Stack: send-request  
```

Also there is problem. How to add data (when it will work) to it? I will need mix `\auth` and `\data` but I do not know how to do it from Red.

**Comment by rebolek** [comment]
I am closing it, as we discussed on Gitter, this is actually JWT and should be sent a bit differently.
