### ISSUE TITLE
issue with http-tools with latest Red 

### ISSUE THREAD

**Issue by bubnenkoff** [rebolek/red-tools#7]
Hi! I tried to compile my project with latest build of red from 12.09.2021 and it on http request it begin to return weird http code.
I tried to small code snippet and got an error:
```
>>  send-request/data to-url "http://10.201.1.35:5001/" 'POST []
*** Script Error: value out of range: 1
*** Where: set-path
*** Stack: send-request
```

**Comment by rebolek** [comment]
Thanks for report. However, version in this repository is no longer supported. `send-request` and other networking tools were moved to https://gitlab.com/rebolek/castr
Please, test your code with the version from Gitlab that has latest fixes and if your problem still exists, post a report there.

Thanks!
